dist: trusty
sudo: required

language: node_js
node_js:
- '8'

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
        - lcov --capture --directory . --output-file coverage.info
        - lcov --list coverage.info
    - stage: sonar
      script:
        - sonar-scanner

stages:
  - compile
  - test
  - sonar

after_success: npm run coverage