dist: trusty
sudo: required

language: node_js
node_js:
- '10'
- '8'
after_success: npm run coverage

addons:
  sonarcloud:
    organization: "petruki"
    token:
      token: ${SONAR_TOKEN}

script:
  - sonar-scanner