dist: trusty
sudo: required

language: node_js
node_js:
- '8'

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}
  artifacts:
    expose_as: 'artifact lcov'
    paths:
      - coverage/lcov.info

script:
  - sonar-scanner

after_success: npm run coverage