dist: trusty
sudo: required

language: node_js
node_js:
- '10'
- '8'

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}

script:
  - sonar-scanner

after_success: npm run coverage